### ISSUE TITLE
Scoring change: add a point if people have checked off “delete protection”

### ISSUE THREAD

**Issue by jimherries** [ChrisMahlke/contribute-dev#112]
Sean: add a point if people have checked off “delete protection”

Will need to carve that point out of existing points in the Performance section

**Comment by ChrisMahlke** [comment]
@jimherries I have logic in place (code) to add this feature.  Where do we want to subtract a point from in the scoring (somewhere in the performance section)?

**Comment by jimherries** [comment]
Let's go with these revised point awards under Sharing:

1	Delete protection on
4	shared public
2	shared with org
0	shared private

**Comment by ChrisMahlke** [comment]
@jimherries  I don't see that delete protection is exposed in the API.  Do you see it?

**Comment by jimherries** [comment]
Not that i can find. may be undocumented of course

**Comment by jimherries** [comment]
Nicely done. Can you also update the Tooltip for the "Sharing" option to  say:

Score: Full points are awarded for sharing the item Public and setting Delete Protection on.
