### ISSUE TITLE
Enhancement: email the user upon nomination

### ISSUE THREAD

**Issue by jimherries** [ChrisMahlke/contribute-dev#120]
It might be nice for the user to get an automatic email after nominating saying something like, “Thank you for nominating! Your map is under review and you should expect to hear from us shortly.”

Alternative: allow the curator the option to email the user from the Curator app

**Comment by ChrisMahlke** [comment]
@jimherries Need access to a mail server if we want automatic emails to be sent out.  For instance, who is the email coming from, esri.com, arcgis.com, etc...?
