### ISSUE TITLE
GIF thumbnail uploads successfully but scores a 0

### ISSUE THREAD

**Issue by jimherries** [ChrisMahlke/contribute-dev#125]
The item I nominated had a custom (awesome) thumbnail (enclosed as proof), and I got 0 points.  Otherwise it worked.
![mda_basevue2013](https://cloud.githubusercontent.com/assets/5177430/7125179/a88c8652-e1e3-11e4-95c2-fb2078d934cb.gif)

**Comment by ChrisMahlke** [comment]
@jimherries I'm unable to reproduce this bug. What's the name of the *.gif file you're trying to upload?  I uploaded a *.gif and received 7 points.
