### ISSUE TITLE
Add StoryMaps to supported content

### ISSUE THREAD

**Issue by jimherries** [ChrisMahlke/contribute-dev#127]

**Comment by ChrisMahlke** [comment]
@jimherries StoryMaps are simply Web Mapping Application types, right?  Can you confirm?  I don't see a story maps item "type," however the type Web Mapping Applications is included

**Comment by jimherries** [comment]
Correct, StoryMaps are just Web Mapping Applications.

Jim Herries | Product Engineer – Cartography
Esri<http://www.esri.com/> | 380 New York St | Redlands CA 92373 | USA
909.793.2853 extension 1-2489 | jherries@esri.com<mailto:jherries@esri.com> | @jherries<http://twitter.com/jherries> |  [btn_profile_greytxt_80x15] <http://www.linkedin.com/in/JimHerries>
909.202.2992 mobile
