### ISSUE TITLE
Curators need an option to flag or tag an item for Maps We Love

### ISSUE THREAD

**Issue by jimherries** [ChrisMahlke/contribute-dev#128]
Curator app – add a tag for Maps We Love that curators can recommend the user add

**Comment by ChrisMahlke** [comment]
@jimherries What category in the tree will this be placed?

**Comment by jimherries** [comment]
We don't want to use a tag. We want to provide a simple link that says "Share with Maps We Love team." If the curator hits that link, a mailto: email link populates an email to say:

To: Mark Harrower, Jim Herries
Subject: Maps We Love nomination from Living Atlas
Body: I came across this item while curating the Living Atlas and thought you should consider it for the Maps We Love campaign.

Item: <insert item URL>

Why we love this map:

Why this map works:

Contact me with any questions!

**Comment by jimherries** [comment]
Also, we will write the 3 pieces of information (item URL, why we love it, why this map works) to a new table called mwlnoms so that the MWL app team can pick it up from there.

**Comment by ChrisMahlke** [comment]
@jimherries I need the link to the the FS today so I extend this feature.

**Comment by jimherries** [comment]
done, see http://energy.mapsdevext.arcgis.com/home/item.html?id=4efd44095eca45d2869c59514b530dd7

**Comment by jimherries** [comment]
REST endpoint is always available from AGOL items, just below the descriptions. In this case it is:

http://servicesdev1.arcgis.com/5uh3wwYLNzBuU0Eu/arcgis/rest/services/mwlnoms/FeatureServer/0

**Comment by ChrisMahlke** [comment]
@jimherries are the supported operations on the FS correct?  if not can you change them.

**Comment by ChrisMahlke** [comment]
@jimherries should be similar to this service:

http://services1.arcgis.com/4yjifSiIG17X0gW4/arcgis/rest/services/nomcur/FeatureServer/0

**Comment by jimherries** [comment]
I just deleted two fields that were too small (256 characters) and added two fields with 5,000 characters each.

**Comment by jimherries** [comment]
Ok supported operations are correct now. THanks for that reminder, I had forgotten. I also transferred the item you your account in case you need to make changes while i'm out this afternoon

**Comment by ChrisMahlke** [comment]
@jimherries Ok, great!

**Comment by ChrisMahlke** [comment]
@jimherries Are you able to change this service to a feature layer (type) and not a table?  To stay consistent with nomcur and the other tables?  I'm unable to update this table using the standard method calls provided by our API.

**Comment by jimherries** [comment]
Yes, I’ll do that now

**Comment by jimherries** [comment]
On devext, here is the new rest endpoint:

http://servicesdev1.arcgis.com/5uh3wwYLNzBuU0Eu/arcgis/rest/services/mwlnoms/FeatureServer/0

**Comment by jimherries** [comment]
In the email that is created, please include the URL to the item being recommended.
