### ISSUE TITLE
Accept button needs to write to a group

### ISSUE THREAD

**Issue by jimherries** [ChrisMahlke/contribute-dev#132]
Each curator has one or more groups assigned to them. Curlist has this information.

curatorID    Region          
cmahlke     WO,USA         

curgroup is the layer that "knows" which groupID is assigned to each region code

WO - write to this groupID
USA - write to this groupID

IF a curator is assigned to 2 or more groups, prompt the curator to designate which group or groups to add the item to.

**Comment by ChrisMahlke** [comment]
Needs to testing
