### ISSUE TITLE
Curator: Show the user ID/org info next to each item

### ISSUE THREAD

**Issue by jimherries** [ChrisMahlke/contribute-dev#135]
As a curator, it would be very helpful to see the userID, user's full name, and the name of their organization as mocked up below:L

Example:

Elevation of New York1
Imagery Layer - Sharing:public - Updated May 8, 2015	- owner: jimherries_devext (Jim Herries from Harbour Energy)
Source: Image Service
0 views

**Comment by ChrisMahlke** [comment]
To get the org you need to make an extra query for every item.  AGOL only returns the item's owner.  In AGOL, to get the org/profile etc.. you have to click on the username listed next to the item.  I can list the owner for now.
