### ISSUE TITLE
Open feature layer draws, but using different extent than item itself does when added to a map

### ISSUE THREAD

**Issue by jimherries** [ChrisMahlke/contribute-dev#162]
To reproduce:

On devext, search for item ATSH is my favorite map.
See how it draws, zoomed way, way out.
Now open that same item in AGOL and notice how it draws to a different extent. What extent is AGOL using, can we use that in our preview map?

example:
http://devext.arcgis.com/home/item.html?id=33c5938cddad49d58a8fbd0cd59d33a3

**Comment by ChrisMahlke** [comment]
@jimherries The above item draw way out for me too, not zoomed in.  It's b/c of the containing div.

I'll need another item to repro this issue.

**Comment by ChrisMahlke** [comment]
Containing div is what's causing the map to be zoomed out.  Containing div (UI) needs to be changed to permit the map to draw at correct extent.
