### ISSUE TITLE
Notes box can be resized without scrollbar

### ISSUE THREAD

**Issue by jimherries** [ChrisMahlke/contribute-dev#169]
As a curator, go to add your comments about the user's Thumbnail. Grab the corner of the notes box to make the box bigger. 

If the notes box is dragged to the bottom, there is no scroll bar to show the other comment boxes.

**Comment by ChrisMahlke** [comment]
Unable to reproduce.

**Comment by jimherries** [comment]
Revised the description, slightly. Easy to reproduce as a curator. See Jennifer if I'm not around to show it.

**Comment by ChrisMahlke** [comment]
A scrollbar appears in the Dialog window so that you can scroll to the bottom.  It's the same behavior as what is built into UI library from Esri that I'm using.
