### ISSUE TITLE
Cannot nominate any items if you have applied a filter and searched for an item.

### ISSUE THREAD

**Issue by jimherries** [ChrisMahlke/contribute-dev#179]
Some combinations of applying a filter and searching for an item causes the Nominate button to not respond when pressed.

Workaround: make an edit to the item you want to nominate. Refresh the browser and that item now appears at the top of the list. You can now nominate it (because you don't have to filter or search for it)

**Comment by ChrisMahlke** [comment]
@jimherries I wasn't able to reproduce this issue.  I filtered and searched for an item that did not appear on the first page and was able to nominate it.  Do you have a specific workflow or item that this occurs on?

**Comment by jimherries** [comment]
To reproduce:

Log in as curate88 / curate88
filter by Web Mapping Application
sort by Number of Views
type "Daily"
1 result should show
click on that item's title
retype "Daily"
click on that item's title
no score or nominate button appears
click on the item title again
the nominate button appears
nominate button does not respond when clicked
