### ISSUE TITLE
Modify email boilerplate

### ISSUE THREAD

**Issue by jimherries** [ChrisMahlke/contribute-dev#183]
Alter the end of the email boilerplate to include this:

"...has been accepted to the Living Atlas and is also now featured in our ArcGIS Online Gallery."

Living Atlas should link to http://livingatlas.esri.com and ArcGIS Online Gallery should link to http://www.arcgis.com/home/gallery.html 

(both links open in a new window)

**Comment by ChrisMahlke** [comment]
Per the RFC2368 you can only embed text/plain into the email body.  I think if links or images are embedded in emails it's done on the server side.  If you seen someplace, or some code that permits you to embed a link or image in an email can you forward it to me?  And not generated on the server side.

**Comment by jimherries** [comment]
Given that, we can simply insert the plain text http links, and let the curator adjust that as needed in the email client.
