### ISSUE TITLE
Curator: Add "curator's notes" 

### ISSUE THREAD

**Issue by jimherries** [ChrisMahlke/contribute-dev#184]
Curators would like to have a long text field where they can share comments, for other curators to see.

Suggest a link "Curator's Notes" appear just below the newly proposed "Assigned to" dropdown. Works just like the other notes curators write for each item score component.

**Comment by ChrisMahlke** [comment]
@jimherries Need UI/UX or more descriptive input

**Comment by jimherries** [comment]
Just as a curator can add notes about Thumbnail, Description, etc... we want to have a link that says "Curator's Notes" When the curator clicks on that link, they can enter notes (e.g. "I will call the customer about this" or whatever). These notes do not appear in the email to the customer.
