### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by ChrisMahlke** [ChrisMahlke/contribute-dev#197]
@jimherries 
You can search for items just as you would in AGOL <b>if</b> you are a Nominator.

If you are a Curator, I don't think you can search for items from different users and filter the items based on whether they are nominated.  For instance, if you fire off a query for a term "Railroad" you get back all items that have the term "Railroad," not just items that have been nominated.  Unable to just query nomcur since it does not contain all of the data for an item.

**Comment by jimherries** [comment]
I just logged in as a curator and searched for "map" and it correctly showed 3 nominated/under review/accepted items with that word in it. Seems to work fine.

**Comment by jimherries** [comment]
I'll leave this in Version3 for now, in case it's connected to other issues in Version3.
