### ISSUE TITLE
Curator: Cannot change status on an Accepted item

### ISSUE THREAD

**Issue by jimherries** [ChrisMahlke/contribute-dev#224]
Log in as a Curator on DEVEXT. Choose Daily Evapotranspiration, which currently shows as Accepted. Try to change its status to any other status. Nothing happens.

**Comment by ChrisMahlke** [comment]
@jimherries On DEVEXT, I can change the status, however, when the item's status is changed to "accepted" it is not added to the group below:

http://energy.mapsdevext.arcgis.com/home/group.html?id=67fee7bd3a9e4ac8b8b04709bcfde487

When I try to share the item with the group on DEVEXT in AGOL it says I am <b>not the owner</b> of any groups.

Am I an owner of the above group?  Unable to test until I am an owner.  I can share <b>my own</b> items, just not other user's items.
