### ISSUE TITLE
Curators: prompt curator for Why We Love It and Why It Works 

### ISSUE THREAD

**Issue by jimherries** [ChrisMahlke/contribute-dev#225]
If a curator chooses to nominate an item for Maps We Love, prompt them to answer the questions:

Why We Love It

Why It Works

Store the information in the two fields in the mwlnoms table 

WhyMapIsLoved
WhyThisMapWorks

**Comment by ChrisMahlke** [comment]
@jimherries  Are you referring to something like the below screenshot?

![maps_we_love_dialog](https://cloud.githubusercontent.com/assets/4925379/8068815/3de48594-0eab-11e5-8de1-d6af369252f5.png)
