### ISSUE TITLE
Provide final edits to all score tips 

### ISSUE THREAD

**Issue by jimherries** [ChrisMahlke/contribute-dev#73]
Jim will make final edits to all the score tips once the scoring spreadsheet is finalized.

Jen's suggestions:
3.      In the info button description, make sure to be consistent with capitalization. I noticed that the words directly following “The idea:” or “The score:” are sometimes capitalized and sometimes not- I would recommend making them all consistently capitalized.
4.      Under the blue “Title” info pop-up: change to “Points are awarded if two or more…”
5.      Under the blue “Summary” info pop-up: change to “Points are awarded for having…” and “”copy”, “demo”, “test”, and/or “eval” are used.”
8.      Under the blue “Credits” info pop-up: change to “Full points are awarded…”
9.      Under the blue “Access and Use Constraints” info pop-up: change to “Points are awarded for…”
13.   In the blue “Categories” info pop-up: change to “How can someone find this item if they don’t know its title or the industry?” and “”copy”, “demo”, “test”, and/or “eval” are used.”
14.   Points are awarded for choosing only one category from the left to indicate the primary category. It seems as if the user will not intuitively know this unless he or she reads the info pop-up. What happens if the user chooses more than one category? There should be a way for the user to select more than one category while also specifying which is the primary category.
16.   Under the blue “Draw Time” info pop-up, there should be advice on how to speed up the map (or at least provide a link to a how-to page)
18.   Ironically, the info pop-up for “pop ups” does not work for me. I’m not sure how pop-ups should be spelled…
19.   In the “Sharing” section: change to “Full points are awarded for…”
20.   In the “Name” section: change to “Points are awarded…”

**Comment by jimherries** [comment]
per Sean: format the what and why section so it's a little more clear

**Comment by jimherries** [comment]
working on this now for delivery by end of today (Friday Apr 3)

**Comment by ChrisMahlke** [comment]
@jimherries Hey Jim, I couldn't pull your code b/c of a minor issue (missing a closing </b>).  so, I copied it, updated the issue, and pushed the update.
