### ISSUE TITLE
Enhancement: more feedback to user on Description 

### ISSUE THREAD

**Issue by jimherries** [ChrisMahlke/contribute-dev#78]
It would be nice, for example, in the “Description” section, if the app had a dynamic popup that stated things like, “You have reached the minimum word count. Include an email address to receive full points.” That way, the user knows exactly what is missing in the description. Once the user gets a full score, the pop-up would change to say something like, “You have met all requirements. Good job!”

**Comment by ChrisMahlke** [comment]
@jimherries I need more detailed description of this feature.  This feature definitely will not make it into Version 2.

**Comment by ChrisMahlke** [comment]
@jimherries I need more detailed description of this feature. This feature definitely will not make it into Version 3 until more input into the requirements are provided.
