### ISSUE TITLE
Enhancement: add option to upload a full-size thumbnail

### ISSUE THREAD

**Issue by jimherries** [ChrisMahlke/contribute-dev#90]
How about the larger size Living Atlas thumbnail. How will people upload those?
Grayson's "thumbnailer" app allows large thumbnail generation / upload.

**Comment by ChrisMahlke** [comment]
@jimherries I thought we were not allowing this since users were not aware you can upload larger size thumbnails?

**Comment by jimherries** [comment]
The solution may be to build in a large thumbnail uploader, similar to Grayson's app, which has that capability. The API supports it, and Contributor app could display it.
